version: '3.8'

services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  migrations:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_started
    command: python manage.py migrate

  db:
    image: postgres:15.2
    ports:
      - "2345:5432"
    env_file:
      - ./backend/.env
    restart: always
